name          'thejandroman-openvpn_client'
version       '0.1.0'
source        'https://github.com/thejandroman/puppet-openvpn_client.git'
author        'thejandroman'
license       'Apache-2.0'
summary       'Install and configure OpenVPN clients.'
description   'Install and configure OpenVPN clients.'
project_page  'https://github.com/thejandroman/puppet-openvpn_client'

dependency 'puppetlabs/stdlib'
